### ISSUE TITLE
First-class debugging

### ISSUE THREAD

**Issue by ErichDonGubler** [not-yet-awesome-rust/not-yet-awesome-rust#38]
This issue is being made in response to [/u/edapa on the Rust Reddit](https://www.reddit.com/r/rust/comments/7zpvev/notyetawesome_rust_what_use_cases_would_you_like/duq228y/):

> The biggest gap for me is a first class debugger (rust-gdb is nice, but not all the way there)

It would be best to actually enumerate what's missing -- otherwise, it's hard to list actual use cases associated with this. However, it sounds like there's potential already, and that thinking of those features shouldn't be hard!

**Comment by ethanpailes** [comment]
On reddit I'm edapa, so I'll elaborate on what I meant here.

First of all, rust tooling (with the exception of debugging) is generally best in class by a long shot, and the `rust-gdb` and `rust-lldb` wrappers do about as good a job as I would expect for a new natively compiled language. My favorite way to debug is not to write bugs in the first place, and rust does a great job of helping me do that. Now that I've got that disclaimer out of the way I'm going to jump right into being whiny about an open source project I haven't contributed to.

# Debugging Wishlist

I'm well aware that this would require some really intense technical chops and effort to produce this environment, so I'm not coming here with any serious expectations.

## Positive Debugging Experiences I've Had in the Past

### pdb

The main way I develop python code is to write stuff, then use `pdb.set_trace()` to set a breakpoint where I'm not sure quite what to do next, and start poking around to figure out what to do (the `dir` function is great at this point). pdb is essentially a full python REPL with some extra syntax to control debugger behavior, only it is about 1000 times better than a python REPL because you don't have to spend any time setting up program state before you start poking around. It lets you use all the power of Python's dynamic inspection capabilities to examine your program as it is in the middle of doing something complex and stateful. You can even import new modules to test them or open more powerful introspection (I often pull in `json` to dump some complex object).

### GDB Source Level Debugging

The GDB source level debugging experience is almost as good as the pdb debugging experience (plus it's fast). In addition to doing all the program execution control things you expect a debugger to do gdb is a full C interpreter which lets you run about and poke program state. The experience only falls short of pdb because the C language does not encourage introspection as much as dynamic languages do.

### GHCI

`ghci` technically includes debugging capabilities, but I've never been able to get excited about them. Where `ghci` really shines is in its ability to do type based introspection. The ability to do `:i symbol` to see the definition of a type or value or `:t symbol` to see the type of a value is great for exploring new APIs. The `:r` command is also great, but I'm not sure that translates to a debugging context as cleanly.

## Tying it Together

I would love it if a rust debugger had the following features (roughly in order of what I see as their importance)

1. A full rust interpreter. The power to evaluate arbitrary rust expressions would make introspection much easier.
2. Type based introspection capabilities. Rust has a nice expressive type system, and a standardized documentation format. In my ideal rust debugger I would be able to ask "what is this symbol's type and value?", "what is this type or value's definition (also where is it)?", "What is the answer to both of those last questions at once?", and "What (if any) is the rustdoc on this symbol?"
3. Dynamic Imports. I'm actually not even convinced that this makes sense for a compiled language, but it’s nice to have in python and this is a wishlist not an RFC.
4. The ability to time travel? I've never used a time traveling debugger but they seem super shiny.

**Comment by ErichDonGubler** [comment]
Hey, thanks for going out of your way to add some details! I haven't taken more than a skim through what you've written, and I expect I won't be able to until a new week begins, but what I saw got me excited to dig in and get this information onto the list.

**Comment by tromey** [comment]
> Type based introspection capabilities. 

In gdb you can currently do `ptype item` and get information about its type.  There's no rustdoc integration but I guess that's something that maybe could be done in rust's python gdb helpers.

> The ability to time travel?

gdb has this built in, but it has some restrictions that make it not very good in general.  However, if you don't need full reversing but rather just "find where the bad branch came from", gdb's `btrace` recording is good.  
For the general case you should use http://rr-project.org/

**Comment by ethanpailes** [comment]
Oh ptype is slick! Thanks for the tip @tromey. Does lldb have a simmilar feature?

I keep meaning to try out `rr`.

**Comment by tromey** [comment]
From https://lldb.llvm.org/lldb-gdb.html it appears that `ptype` is `image lookup --type` in lldb.

**Comment by ethanpailes** [comment]
Cool!

It seems like lldb's command language is designed for computers rather than humans. That is a lot to type.

**Comment by ErichDonGubler** [comment]
Alright, so, here're the use cases I see mentioned so far. I'll lean heavily on your concluding list for this. :)

* > 1. A full rust interpreter. The power to evaluate arbitrary rust expressions would make introspection much easier.

    [`miri`](https://github.com/solson/miri) is exactly this use case. Granted, it's not stable, and so I'd definitely say that there's a spot for this in NYAR.

* > 2. Type based introspection capabilities. Rust has a nice expressive type system, and a standardized documentation format. In my ideal rust debugger I would be able to ask "what is this symbol's type and value?", "what is this type or value's definition (also where is it)?", "What is the answer to both of those last questions at once?", and "What (if any) is the rustdoc on this symbol?" (I like the `:t`, `:i`, `:d` syntax from ghci personally)

    I *think* I know the answer to this question already from the discussion, but just so we're all on the same page: is type introspection already available? It certainly seems so, from @tromey's responses:

    > In gdb you can currently do `ptype item` and get information about its type.  There's no rustdoc integration but I guess that's something that maybe could be done in rust's python gdb helpers.

    As for `rustdoc` debugging integration, that sounds like a cool thing, but can `gdb` actually offer documentation integration for other languages?

* > 4. The ability to time travel? I've never used a time traveling debugger but they seem super shiny.

    Per the discussion already here, it seems this is already exposed, though `rr` might be a preferable approach:

    > gdb has this built in, but it has some restrictions that make it not very good in general.  However, if you don't need full reversing but rather just "find where the bad branch came from", gdb's `btrace` recording is good.  
For the general case you should use http://rr-project.org/

* > 3. Dynamic Imports. I'm actually not even convinced that this makes sense for a compiled language, but it’s nice to have in python and this is a wishlist not an RFC.

   This would make sense for a Rust interpreter like `miri`, actually! An interpreted toolchain would probably have its own separate debugging solution, which would be outside of anything we've discussed so far. I don't see this as actionable yet.

I've started compiling the actionable items I already know about into [this PR](https://github.com/not-yet-awesome-rust/not-yet-awesome-rust/pull/41). So far I've seen a *stable* interpreter for Rust be the only unchallenged hole in the ecosystem.

**Comment by ethanpailes** [comment]
The last time there was a discussion of miri [on reddit](https://www.reddit.com/r/rust/comments/7ju75d/miri_was_merged_into_rustc/?st=je67kz2g&sh=9bb294a4) I remember that it had trouble evaluating expressions using FFI. It seems like that should be doable through something like [dyncall](http://www.dyncall.org/), but I don't really know miri internals.

**Comment by ErichDonGubler** [comment]
@ethanpailes: How's the PR looking? Anything we should discuss before I merge it?

**Comment by ethanpailes** [comment]
I'm basically happy except for that comment I left on the PR. It would also be nice to mention the fact that the rust-lldb image lookup --type output looks like this:

```
(lldb) image lookup --type Regex
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
2 matches found in /Users/ethan/Documents/repos/regex/target/debug/deps/regex-9f3bf5b4df1f3bdc:
id = {0x0000806c}, name = "Regex", qualified = "regex::re_bytes::Regex", byte-size = 56, compiler_type = "struct Regex {
    regex::exec::Exec __0;
    static core::result::Result<regex::re_bytes::Regex, regex::error::Error> new(&str);
    static bool is_match(regex::re_bytes::Regex *, &[u8]);
    static core::option::Option<regex::re_bytes::Match> find(regex::re_bytes::Regex *, &[u8]);
    static regex::re_bytes::Matches find_iter(regex::re_bytes::Regex *, &[u8]);
    static core::option::Option<regex::re_bytes::Captures> captures(regex::re_bytes::Regex *, &[u8]);
    static regex::re_bytes::CaptureMatches captures_iter(regex::re_bytes::Regex *, &[u8]);
    static regex::re_bytes::Split split(regex::re_bytes::Regex *, &[u8]);
    static regex::re_bytes::SplitN splitn(regex::re_bytes::Regex *, &[u8], unsigned long);
    static core::option::Option<usize> shortest_match(regex::re_bytes::Regex *, &[u8]);
    static core::option::Option<usize> shortest_match_at(regex::re_bytes::Regex *, &[u8], unsigned long);
    static bool is_match_at(regex::re_bytes::Regex *, &[u8], unsigned long);
    static core::option::Option<regex::re_bytes::Match> find_at(regex::re_bytes::Regex *, &[u8], unsigned long);
    static core::option::Option<regex::re_bytes::Match> read_captures_at(regex::re_bytes::Regex *, regex::re_trait::Locations *, &[u8], unsigned long);
    static &str as_str(regex::re_bytes::Regex *);
    static regex::re_bytes::CaptureNames capture_names(regex::re_bytes::Regex *);
    static unsigned long captures_len(regex::re_bytes::Regex *);
    static regex::re_trait::Locations locations(regex::re_bytes::Regex *);
}"
id = {0x00009062}, name = "Regex", qualified = "regex::re_unicode::Regex", byte-size = 64, compiler_type = "struct Regex {
    regex::re_unicode::_Regex __0;
    static core::result::Result<regex::re_unicode::Regex, regex::error::Error> new(&str);
    static bool is_match(regex::re_unicode::Regex *, &str);
    static core::option::Option<regex::re_unicode::Match> find(regex::re_unicode::Regex *, &str);
    static regex::re_unicode::Matches find_iter(regex::re_unicode::Regex *, &str);
    static core::option::Option<regex::re_unicode::Captures> captures(regex::re_unicode::Regex *, &str);
    static regex::re_unicode::CaptureMatches captures_iter(regex::re_unicode::Regex *, &str);
    static regex::re_unicode::Split split(regex::re_unicode::Regex *, &str);
    static regex::re_unicode::SplitN splitn(regex::re_unicode::Regex *, &str, unsigned long);
    static core::option::Option<usize> shortest_match(regex::re_unicode::Regex *, &str);
    static core::option::Option<usize> shortest_match_at(regex::re_unicode::Regex *, &str, unsigned long);
    static bool is_match_at(regex::re_unicode::Regex *, &str, unsigned long);
    static core::option::Option<regex::re_unicode::Match> find_at(regex::re_unicode::Regex *, &str, unsigned long);
    static core::option::Option<regex::re_unicode::Match> read_captures_at(regex::re_unicode::Regex *, regex::re_trait::Locations *, &str, unsigned long);
    static &str as_str(regex::re_unicode::Regex *);
    static regex::re_unicode::CaptureNames capture_names(regex::re_unicode::Regex *);
    static unsigned long captures_len(regex::re_unicode::Regex *);
    static regex::re_trait::Locations locations(regex::re_unicode::Regex *);
}"
```

That's for the `Regex` type from the crate of the same name. It tells you somthing, but it's not

```
2 matches found in /Users/ethan/Documents/repos/regex/target/debug/deps/regex-9f3bf5b4df1f3bdc:
in src/re_unicode.rs:138:
     pub struct Regex(#[doc(hidden)] pub _Regex);
in src/re_bytes.rs:86:
     pub struct RegexSet(Exec);
```

As I think it probably should be. If I want to know more about the structure I can drill down on this Exec thing.

**Comment by ErichDonGubler** [comment]
> I'm basically happy except for that comment I left on the PR.

@ethanpailes: Uh...what comment is that? I don't see ANY comments on the PR. :(

**Comment by ethanpailes** [comment]
@ErichDonGubler, oh sorry about that. It seems I don't know how to use Github Reviews. I published it.

**Comment by ErichDonGubler** [comment]
Closing here, since the discussion seems to have wrapped up.
