### ISSUE TITLE
cp437 crate implemented

### ISSUE THREAD

**Issue by nabijaczleweli** [not-yet-awesome-rust/not-yet-awesome-rust#40]
I found #21 and [implemented it](https://crates.io/crates/codepage-437), and @ssokolow, the main promoter, seems, despite apparent chronic fatigue, to be relatively satisfied with the implementation.

**Comment by ssokolow** [comment]
It's been a messy few weeks and normally, I'd compensate for that by doing some experimental coding with the API to see if any problems become apparent, but I just haven't had the time.

Basically, "Looks good to me... but I know I'm not as perceptive as I really should be in order to make that judgment with any degree of authority".

**Comment by ErichDonGubler** [comment]
Woot! You guys are awesome! I don't have a moment right now to examine the crate proposed, but it gets me excited to think that another content suggestion here has  helped get something interesting implemented! I'll probably get to this after the weekend. :)

**Comment by ErichDonGubler** [comment]
DONE!
