### ISSUE TITLE
Timely Dataflow as extra data processing resource ?

### ISSUE THREAD

**Issue by wdv4758h** [not-yet-awesome-rust/not-yet-awesome-rust#45]
I'm not familar with this domain, but this project looks like a good resouce.

> This project is something akin to a distributed data-parallel compute engine, which scales the same program up from a single thread on your laptop to distributed execution across a cluster of computers. The main goals are expressive power and high performance. It is probably strictly more expressive and faster than whatever you are currently using, assuming you aren't yet using timely dataflow.

* Timely Dataflow: https://github.com/frankmcsherry/timely-dataflow
* PageRank example: https://github.com/frankmcsherry/pagerank

**Comment by ErichDonGubler** [comment]
Hey there! Thanks for taking the time to . :-)

**Comment by ErichDonGubler** [comment]
@wdv4758h: Now that I've had a little bit of time to look at this crate, it does indeed seem like an interesting choice for an **unbounded** data processing stream. The use case currently listed for data processing pipelines are for ones with *backpressure*, which it looks like Timely doesn't support at this time.

My question is...what were you hoping the resolution to this issue is? I'm not sure. Listing existing resources for certain problem domains is more in the scope of an "awesome" list like [Awesome Rust](https://github.com/rust-unofficial/awesome-rust), while this list is for use cases that *haven't* been fulfilled yet. Were you asking if this fulfills the use case in the [data processing](https://github.com/not-yet-awesome-rust/not-yet-awesome-rust#data-processing) section?

**Comment by wdv4758h** [comment]
When I found this repo and read the list, I recalled the Timely repo. I just want to share this information to see if this can help any outstanding task. I'm fine with closing this issue if it doesn't help :)

**Comment by ErichDonGubler** [comment]
Yeah, so far so good here -- if you find a framework that can limit data flow to respect resources, let me know! In the meantime, you should really look into getting Timely into Awesome Rust. :)
