### ISSUE TITLE
Concurrent Map Candidate: chashmap

### ISSUE THREAD

**Issue by software-is-art** [not-yet-awesome-rust/not-yet-awesome-rust#83]
RedoxOS has an implementation of a Concurrent Map that closely models HashMap.

I skimmed the source code, but the implementation seems to implement best practices and closely resembles methods I've seen used for concurrent maps in other languages such as C# and Java.

Crate: https://crates.io/crates/chashmap
GitLab: https://gitlab.redox-os.org/redox-os/chashmap/-/tree/master

**Comment by wezm** [comment]
Jon Hoo has been working on one too https://github.com/jonhoo/flurry

**Comment by ErichDonGubler** [comment]
@wezm, @software-is-art: While I don't believe `chashmap` or `flurry` fulfill the "hole" documented (having something as close to `std::collections::HashMap` as possible), I believe [`dashmap`](https://github.com/xacrimon/dashmap) does satisfy the vast majority of the items currently on the NYAR list -- it even states at [the beginning of its API docs](https://docs.rs/dashmap/3.7.0/dashmap/struct.DashMap.html):

> DashMap tries to implement an easy to use API similar to `std::collections::HashMap` with some slight changes to handle concurrency.

It's been a while since I've looked at this part of the ecosystem, so thanks for the bump! I think I'll close this specifically for `dashmap` as the solution. I want to recognize your efforts, though I hesitate to add the crates you've suggested only because documentation goes stale, so more content means more potentially out-of-date content later.
